masterSlaveServersConfig:
  # DNS 모니터링 설정
  dnsMonitoringInterval: 30000

  # 타임아웃 설정
  idleConnectionTimeout: 60000
  connectTimeout: 5000
  timeout: 3000
  
  # 재시도 설정
  retryAttempts: 2
  retryDelay: !<org.redisson.config.EqualJitterDelay> { baseDelay: PT0.1S, maxDelay: PT0.4S }
  reconnectionDelay: !<org.redisson.config.EqualJitterDelay> { baseDelay: PT0.2S, maxDelay: PT2S }

  failedSlaveReconnectionInterval: 10000
  failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> { }

  password: null

  # 구독 연결
  subscriptionsPerConnection: 10
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 5

  clientName: "@projectName@"
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> { }

  # 핵심: pod당 커넥션 최소화
  slaveConnectionMinimumIdleSize: 2
  slaveConnectionPoolSize: 8
  masterConnectionMinimumIdleSize: 2
  masterConnectionPoolSize: 8

  # 읽기/구독 모드
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"

  # 
  slaveAddresses:
    - "redis://localhost:6379"
    - "redis://localhost:6379"
  masterAddress: "redis://localhost:6379"
  database: 0

  # ElastiCache 특화 설정
  pingConnectionInterval: 30000
  keepAlive: true
  tcpNoDelay: true

threads: 6
nettyThreads: 12
codec: !<org.redisson.codec.LZ4Codec> { }
transportMode: "NIO"